# -*- coding: utf-8 -*-
"""Semana 05-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQCQScvZNaNMSlqCRKnG7Lnu1tqUOsMJ
"""



"""SEMANA 05
1. Coleccion de datos
2. Estructuras Desicivas y Estructura Repetitivas
3. Clases y Objetos
4. Funciones

1. Coleccion de Datos
"""

#1.1 Listas
#Es una coleecion de elementos que puede ser ordenada, modificada, etc...
#Se identifica por los corchetes
#Ejemplo

aula = ["Huertas","Jimenez","Rodriguez","Caballero"]

aula

#podemos extraer cada elemneto por su posicion
print(aula[0])

#para agregar elementos a la lista
aula.append("Mamani")
aula.append("Fernandez")
aula

aula.remove("Huertas")
aula

#para eliminar un solo siempre escoge el de menor ubicacion
aula.remove("Mamani")
aula

#para recorrer podemos utilizar una estructura repetitiva
for alumno in aula:
  print(alumno)

#para invertir la lista utilizamos reverse()
aula.reverse()
aula

#para ordenar listas utilizamos sort()
aula.sort()
aula

##TUPLAS
tupla_aula = ("huertas","bravo","bonifacio","caballero")
tupla_aula

#conjuntos
conjunto_aula = {"huertas","bravo","bonifacio","caballero"}
conjunto_aula

#se puede recorrer utilizando una estructura repetitiva
for alumno in conjunto_aula:
  print(alumno)

#observacion no s epuede acceder por posicion pues no considera indexacion
conjunto_aula[2]

#para saber la cantidad de elementos len()
len(conjunto_aula)

#para agregar add()
conjunto_aula.add("Paye")
conjunto_aula

conjunto_aula.remove("bravo")
conjunto_aula

#diccionarios
#es una collecion de elementos, que estan indexados,
#no estan ordenados y se pueden modificar
#son escritos entre llaves y estan formados por pares de elementos
#INDICE:VALOR
diccionario_aula = {2:"huertas", '1':"bravo", 'dos':"bonifacio" ,'3':"caballero"}
diccionario_aula

#extraer el valor del diccionario
diccionario_aula["1"]

diccionario_aula["dos"]

#para añadir un par de elementos al diccionario hacemos
diccionario_aula["20"] = "velez"
diccionario_aula

#para eliminar un valor se utiliza pop() o del()
#por ejemplo, eliminar el elemento de indice dos ejemplo: para eliminar a Bernaoli
diccionario_aula.pop(2)
diccionario_aula

#para obtener el indice y el valor de cada elemento utilizamos items()
for indice, valor in diccionario_aula.items():
  print(indice,valor)

# 1.5. Ejercicio
# Dado una lista de [AMES, ARTEAGA , BARRIOS , BONIFACIO, BRAVO, CABALLERO , CAÑAZACA, FERNANDEZ , FLORES , GARCIA , HERRERA , HUERTA , HUERTAS, JIMENEZ , MAMANI , MANCILLA, PABLO , PAYE , PEÑA , PIZANGO, RAMOS, SANCHEZ,SEVILLANO, TINOCO, TORRES , VALDIVIESO, VELEZ , VILLANUEVA , ZUÑIGA]
# Diseñar un código que muestre si el apellido de un estudiante (Ingresado por teclado) forma parte de la lista
# tiempo: 12 minutos

alumnos = ["AMES", "ARTEAGA" , "BARRIOS" , "BONIFACIO", "BRAVO", "CABALLERO" , "CAÑAZACA", "FERNANDEZ" , "FLORES" , "GARCIA" , "HERRERA" , "HUERTA" , "HUERTAS", "JIMENEZ" , "MAMANI" , "MANCILLA", "PABLO" , "PAYE" , "PEÑA" , "PIZANGO", "RAMOS", "SANCHEZ","SEVILLANO", "TINOCO", "TORRES" , "VALDIVIESO", "VELEZ" , "VILLANUEVA" , "ZUÑIGA"]
nombre = input("Escribe el nombre del alumno: ")

if nombre.upper() in alumnos:
  print("El alumno ingresado si forma parte de la lista")
else:
  print("El alumno ingresado no esta dentro de la lista")

P1 = float(input("Producto 1: "))
P2 = float(input("Producto 2: "))
P3 = float(input("Producto 3: "))
total = P1 + P2 + P3
if total >= 1000:
  total *= 0.9
  print(f"el total a pagar es: {total}")

ventas =  float(input("Importe de ventas realizadas: "))
if ventas < 0:
  print("Datos erroneos")
else:
  if ventas < 1000:
    print("Categoria A")
  else:
    if ventas < 2000:
      print("Categoria B")
    else:
      if ventas < 5000:
        print("Categoria C")
      else:
        if ventas > 5000:
          print("Categoria D")
        else:
          print("No se encuentra en ninguna categoria")

ventas =  float(input("Importe de ventas realizadas: "))
if ventas < 0:
  print("Datos erroneos")
elif ventas <=1000:
  print("Categoria A")
elif ventas <= 2000:
  print("Categoria B")
elif ventas <= 5000:
  print("Categoria C")
elif ventas > 5000:
  print("Categoria D")



"""#2.2 Estructura repetitivas
#for

"""

#problema 01:
#mostrar los elementos de la lista

aula = ["barrios","sevillano","zuñiga","paye"]

#Por cada alumno que esta en la lista, imprimir alumno
for alumno in aula:
  print(alumno)

#problema 02:
#mostrar los elementos de la cadena por teclado

cadena = input("Ingrese cadena: ")
for caracter in cadena:
  print(caracter)

#para generar rangos d enumeros utilizamos range()
range(5)

#imprime los numeros del 1 al 10
for numero in range(11):
  print(numero)

#imprime los numeros del 0 al 5
for numero in range(5,11):
  print(numero)

#imprime los numeros del 10 al 20 utilizando for
for numero in range(10,22,2):
  print(numero)

#while
#permite ejecutar un conjunto de acciones mientras se cumpla la condicion

numero = 1
fin = 10
while numero <= fin:
  print (numero)
  numero +=1

