# -*- coding: utf-8 -*-
"""Semana 05-04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cv99Ayasd6Jb1nSpdg5cpVly9WZcrGae
"""



"""#SEMANA 05

1. Coleccion de datos
2. Estructuras Desicivas y Estructura Repetitivas
3. Funciones
4. Clases y Objetos

4. Clases y Objetos
"""

#problema 01

#crear la siguiente clase:
class Persona:
  nombre = ""
  apellidos = ""
  dni = ""
  talla = ""

#creacion del objeto personal
persona1 = Persona()

#Asignamos valores al objeto
persona1.nombre = "Dharma"
persona1.apellidos = "Bonifacio Toledo"
persona1.dni = "12345678"
persona1.talla = 1.68

#para mostrar valores del objeto
print("persona1")
print(f"Nombre: {persona1.nombre}")
print(f"Apellidos: {persona1.apellidos}")
print(f"DNI: {persona1.dni}")
print(f"Talla: {persona1.talla}")

#Para utilizar constructores utilizamos: _init_
#¿Que es un constructor?
#- Es un metodo
#- Sirve para inicializar valores a una clase

#Problema2
#Crear la siguiente clase y utilizar construcciones:
# - clase:curso
# - Atributos: Codigo, Nombre, horas, creditos,

#Solucion:
class curso:
  def __init__(self, codigo, nombre, horas, creditos):
    self.codigo = codigo
    self.nombre = nombre
    self.horas = horas
    self.creditos = creditos
  def mostrar_datos_curso(self):
    print(f"curso: {self.nombre}")
    print(f"horas: {self.horas}")
    print(f"codigo: {self.codigo}")
    print(f"creditos: {self.creditos}")

#Creamos el objeto curso1 y le mandamos parametros
curso1 = curso("C0501", "LP3",6,3)

#Mostramos los datos completos del curso, ejecutando el metodo mostrar_datos_cursos
curso1.mostrar_datos_curso();