# -*- coding: utf-8 -*-
"""Semana 05-03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LPsaFbzpAPQUfbn_0X27J4vsEyuUenfx

#SEMANA 05

1. Coleccion de datos
2. Estructuras Desicivas y Estructura Repetitivas
3. Funciones
4. Clases y Objetos

3. Funciones
"""

#tambien conocidos como metodos
#metodos vacios
#metodos que reciben valores
#metodos que devuelven un valor
#metodos que reciben y devuelven valores

#3.1 Metodos vacios

def saludo():
  print("Bienvenidos al curso de LP3")
  print("***** Python *****")

saludo()

#3.2 Metodos que reciebn valores

def factorial(numero):
  fac = 1
  for i in range(1,numero+1):
    fac *= i
  print(f"El factorial es: {fac}")

numero = int(input("Ingrese Numero: "))

factorial(numero)

#3.3 Metodos que devuelven valores
def saludo2():
  mensaje = "Bienvenidos a LP3"
  return mensaje

saludo2()

def factorial2(numero):
  fac=1
  for i in range(1,numero+1):
    fac *= i
  return fac

numero = int(input("Numero: "))
print(f"El factorial de {numero} es {factorial2(numero)}")

#otro ejemplo
#calcular igv
def obtenerigv(importe):
  return importe*0.19

obtenerigv(150)

factorial2(5)+20